version: '3.9'

services:
  prothomalo-backend:
    build:
      context: ./prothomalo_backend
      dockerfile: Dockerfile  
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./prothomalo_backend:/code  
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - elasticsearch

  prothomalo-frontend:
    build: 
      context: ./prothomalo_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./prothomalo_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://prothomalo-scraper:8000
      - prothomalo-scraper
    depends_on:
      - prothomalo-backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=JvQhvZYl
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:JvQhvZYl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  esdata:

